name = "edgeone-doh"
main = "worker/worker.js"
compatibility_date = "2026-08-06"

# KV 绑定（变量名 KV）
[[kv_namespaces]]
binding = "KV"
id = "ns-da7FDZVOT58s"

# 环境变量
[vars]
ADMIN_TOKEN = "doh-admin-7f3k9"
DOH_DOMAIN = "edgeone-doh.anglesgirl.workers.dev"
