name = "ech-doh"
main = "worker/worker.js"
compatibility_date = "2026-08-06"

# KV 绑定（Cloudflare Workers KV，变量名 KV）
[[kv_namespaces]]
binding = "KV"
id = "cafe158e4dfc458d88e6e7ba452276cf"

# 环境变量
[vars]
ADMIN_TOKEN = "doh-admin-7f3k9"
DOH_DOMAIN = "ech-doh.lintoya.workers.dev"
